//
//  AdminAddStandsAndAssignInventory
//  Hyppoe
//
//  Generated by Supernova.
//  Refactored by Jiawen Ge.
//

import React from "react"
import { Image, StyleSheet, Text, View, ScrollView } from "react-native"
import { TouchableOpacity, TextInput } from "react-native-gesture-handler"

export default class AdminAddStandsAndAssignInventory extends React.Component {

	static navigationOptions = ({ navigation }) => {
	
		const { params = {} } = navigation.state
		return {
				header: null,
				headerLeft: null,
				headerRight: null,
			}
	}

	constructor(props) {
		super(props)

		this.state = {
			Stations: [
				{
					name: 'Big Tent',
					tablets: 4,
					runners: 4,
					drinks: [
						{ name: 'Bud Light', unit: 0, pack: 0, percent: 0 },
						{ name: 'Coors', unit: 0, pack: 0, percent: 0 },
						{ name: 'Coca Cola', unit: 0, pack: 0, percent: 0 },
						{ name: 'Water', unit: 0, pack: 0, percent: 0 }
					],
					total: 0
				},
				{
					name: 'Main Stage',
					tablets: 4,
					runners: 4,
					drinks: [
						{ name: 'Bud Light', unit: 0, pack: 0, percent: 0 },
						{ name: 'Coors', unit: 0, pack: 0, percent: 0 },
						{ name: 'Coca Cola', unit: 0, pack: 0, percent: 0 },
						{ name: 'Water', unit: 0, pack: 0, percent: 0 }
					],
					total: 0
				}
			],
			Temp: [
				{
					name: 'Big Tent',
					tablets: 4,
					runners: 4,
					drinks: [
						{ name: 'Bud Light', unit: 0, pack: 0 },
						{ name: 'Coors', unit: 0, pack: 0 },
						{ name: 'Coca Cola', unit: 0, pack: 0 },
						{ name: 'Water', unit: 0, pack: 0 }
					]
				},
				{
					name: 'Main Stage',
					tablets: 4,
					runners: 4,
					drinks: [
						{ name: 'Bud Light', unit: 0, pack: 0 },
						{ name: 'Coors', unit: 0, pack: 0 },
						{ name: 'Coca Cola', unit: 0, pack: 0 },
						{ name: 'Water', unit: 0, pack: 0 }
					]
				}
			]
		}
	}

	parseNumField(text) {
		var num = parseInt(text);
		if (isNaN(num) || num <= 0) {
			num = 0;
		}
		return num;
	}

	updateTablet(stationId, text) {
		var num = this.parseNumField(text);
		let temp = [...this.state.Temp];
		temp[stationId] = {...temp[stationId], tablets: num};
		this.setState({Temp: temp});
	}

	updateRunner(stationId, text) {
		var num = this.parseNumField(text);
		let temp = [...this.state.Temp];
		temp[stationId] = {...temp[stationId], runners: num};
		this.setState({Temp: temp});
	}

	updateDrinkUnit(stationId, drinkId, text) {
		var num = this.parseNumField(text);
		let temp = [...this.state.Temp];
		let drinks = [...temp[stationId].drinks];
		drinks[drinkId] = {...drinks[drinkId], unit: num};
		temp[stationId] = {...temp[stationId], drinks: drinks};
		this.setState({Temp: temp});
	}

	updateDrinkPack(stationId, drinkId, text) {
		var num = this.parseNumField(text);
		let temp = [...this.state.Temp];
		let drinks = [...temp[stationId].drinks];
		drinks[drinkId] = {...drinks[drinkId], pack: num};
		temp[stationId] = {...temp[stationId], drinks: drinks};
		this.setState({Temp: temp});
	}

	updateFields(stationId) {
		let stations = [...this.state.Stations];
		let sum = 0;
		let drinks = [...this.state.Temp[stationId].drinks];
		for (let j = 0; j < drinks.length; j++) {
			let drink = drinks[j];
			sum += drink.unit * drink.pack;
		}
		stations[stationId] = {...this.state.Temp[stationId], total: sum};
		for (let j = 0; j < drinks.length; j++) {
			let drink = drinks[j];
			let per = 0;
			if (sum != 0) {
				per = Math.floor(drink.unit * drink.pack * 100 / sum);
			}
			drinks[j] = {...drinks[j], percent: per};
		}
		stations[stationId] = {...stations[stationId], drinks: drinks};
		console.log(stations);
		this.setState({Stations: stations});

		let temp = [...this.state.Temp];
		drinks = [...this.state.Temp[stationId].drinks];
		for (let j = 0; j < drinks.length; j++) {
			drinks[j] = {...drinks[j], unit: 0, pack: 0};
		}
		temp[stationId] = {...temp[stationId], drinks: drinks};
		this.setState({Temp: temp});
	}

	componentDidMount() {
	
	}

	render() {
	
		return <View
				style={styles.viewView}>
				<View
					pointerEvents="box-none"
					style={{
						height: 368,
					}}>
					<Image
						source={require("./../../assets/images/top-image-4.png")}
						style={styles.topImageImage}/>
					<View
						pointerEvents="box-none"
						style={{
							position: "absolute",
							left: 30,
							right: 31,
							top: 56,
							height: 312,
							alignItems: "center",
						}}>
						<View
							pointerEvents="box-none"
							style={{
								alignSelf: "stretch",
								height: 20,
								marginLeft: 11,
								marginRight: 55,
								flexDirection: "row",
								alignItems: "flex-start",
							}}>
							<Image
								source={require("./../../assets/images/back-button.png")}
								style={styles.backButtonImage}/>
							<View
								style={{
									flex: 1,
								}}/>
							<Image
								source={require("./../../assets/images/menu-button.png")}
								style={styles.menuButtonImage}/>
						</View>
						<View style ={styles.scrollView}>
							<ScrollView 
								style={styles.scrollView}
								keyboardDismissMode='on-drag'>
								<View>
									{
									this.state.Stations.map((item, index) => (

										<View key={index}
											style={styles.preorderQueCardView}>
											<View
												pointerEvents="box-none"
												style={{
													position: "absolute",
													left: 0,
													right: 0,
													top: 0,
													bottom: 0,
													justifyContent: "center",
												}}>
												<Image
													source={require("./../../assets/images/background-44.png")}
													style={styles.backgroundImage}/>
											</View>
											<View
												pointerEvents="box-none"
												style={{
													position: "absolute",
													left: 20,
													right: 19,
													top: 24,
													bottom: 20,
													alignItems: "flex-end",
												}}>
												<View
													style={styles.drinkCardElementsView}>
													<View
														pointerEvents="box-none"
														style={{
															left: 0,
															right: 0,
															top: 0,
															bottom: 0,
														}}>
														<Text
															style={styles.drinkNameText}>Station {index+1}: {item.name}</Text>
														<Image
															source={require("./../../assets/images/seperator-6.png")}
															style={styles.seperatorImage}/>
														<Text
															style={styles.inputDrinkNameTwentyText}>Total:</Text>
														<View
															pointerEvents="box-none"
															style={{
																height: 16,
																marginLeft: 63,
																marginRight: 0,
																marginTop: 48,
																marginBottom: 16,
																flexDirection: "row",
																alignItems: "flex-start",
															}}>
															<Text
																style={styles.inputDrinkNameEighteenText}>Available: Unit / Pack</Text>
															<View
																style={{
																	flex: 1,
																}}/>
															<Text
																style={styles.inputDrinkNameTwentyThreeText}>Assign: Unit / Pack</Text>
															<View
																style={{
																	flex: 1,
																}}/>
															<Text
																style={styles.inputDrinkNameThreeText}>Total Inventory</Text>
														</View>
														<View>
															{
															item.drinks.map((drink, i) => (
																<View
																	key={i}
																	pointerEvents="box-none"
																	style={{
																		height: 16,
																		marginLeft: 6,
																		marginRight: 5,
																		marginTop: 2,
																		flexDirection: "row",
																		alignItems: "flex-start",
																	}}>
																	<Text
																		style={styles.inputDrinkNameText}>{drink.name}:</Text>
																	<View
																		style={styles.unitPerPackView}>
																		<Text
																			style={styles.inputDrinkNameElevenText}>{drink.unit}</Text>
																		<View
																			style={{
																				flex: 1,
																			}}/>
																		<Text
																			style={styles.inputDrinkNameTwelveText}>{drink.pack}</Text>
																	</View>
																	<View
																		style={{
																			flex: 1,
																		}}/>
																	<View
																		style={styles.numberBoxView}>
																		<View
																			pointerEvents="box-none"
																			style={{
																				position: "absolute",
																				left: 0,
																				right: 0,
																				top: 0,
																				bottom: 0,
																				justifyContent: "center",
																			}}>
																			<Image
																				source={require("./../../assets/images/rectangle.png")}
																				style={styles.rectangleImage}/>
																		</View>
																		<View
																			pointerEvents="box-none"
																			style={{
																				position: "absolute",
																				left: 0,
																				right: 0,
																				top: 0,
																				bottom: 0,
																				justifyContent: "center",
																			}}>
																			<TextInput 
																				value={this.state.Temp[index].drinks[i].unit.toString()}
																				keyboardType="number-pad"
																				maxLength={3}
																				onChangeText={(text) => {this.updateDrinkUnit(index, i, text)}}
																				style={styles.textTenText}/>
																		</View>
																	</View>
																	<View
																		style={styles.numberBoxView}>
																		<View
																			pointerEvents="box-none"
																			style={{
																				position: "absolute",
																				left: 0,
																				right: 0,
																				top: 0,
																				bottom: 0,
																				justifyContent: "center",
																			}}>
																			<Image
																				source={require("./../../assets/images/rectangle.png")}
																				style={styles.rectangleImage}/>
																		</View>
																		<View
																			pointerEvents="box-none"
																			style={{
																				position: "absolute",
																				left: 0,
																				right: 0,
																				top: 0,
																				bottom: 0,
																				justifyContent: "center",
																			}}>
																			<TextInput 
																				value={this.state.Temp[index].drinks[i].pack.toString()}
																				keyboardType="number-pad"
																				maxLength={3}
																				onChangeText={(text) => {this.updateDrinkPack(index, i, text)}}
																				style={styles.textTenText}/>
																		</View>
																	</View>
																	<View
																		style={{
																			flex: 1,
																		}}/>
																	<Text
																		style={styles.inputDrinkNameFourText}>{drink.percent}%</Text>
																</View>
															))
															}
															<View
																pointerEvents="box-none"
																style={{
																	height: 17,
																	marginLeft: 6,
																	marginRight: 5,
																	marginTop: 2,
																	marginBottom: 16,
																	flexDirection: "row",
																	alignItems: "flex-end",
																}}>
																<Text
																	style={styles.inputDrinkNameTwentyOneText}>Total Units:</Text>
																<View
																	style={{
																		flex: 1,
																	}}/>
																<Text
																	style={styles.inputDrinkNameTwentyTwoText}>{item.total}</Text>
															</View>
														</View>
													</View>
												</View>
												<View
													style={{
														flex: 1,
													}}/>
												
											</View>
											<View
												style={styles.editTwoView}>
												<TouchableOpacity onPress={() => this.updateFields(index)}>
													<Text
														style={styles.editTwoText}>Update</Text>
												</TouchableOpacity>
											</View>
											<View
												pointerEvents="box-none"
												style={{
													position: "absolute",
													left: 26,
													right: 24,
													top: 75,
													height: 19,
													flexDirection: "row",
													alignItems: "flex-start",
												}}>
												<Text
													style={styles.inputDrinkNameTwentySixText}>Tablets:</Text>
												<View
													style={{
														flex: 1,
													}}/>
												<View
													style={styles.numberBoxView}>
													<View
														pointerEvents="box-none"
														style={{
															position: "absolute",
															left: 0,
															right: 0,
															top: 0,
															bottom: 0,
															justifyContent: "center",
														}}>
														<Image
															source={require("./../../assets/images/rectangle.png")}
															style={styles.rectangleImage}/>
													</View>
													<View
														pointerEvents="box-none"
														style={{
															position: "absolute",
															left: 0,
															right: 0,
															top: 0,
															bottom: 0,
															justifyContent: "center",
														}}>
														<TextInput 
															value={this.state.Temp[index].tablets.toString()}
															keyboardType="number-pad"
															maxLength={3}
															onChangeText={(text) => {this.updateTablet(index, text)}}
															style={styles.textTenText}/>
													</View>
												</View>
											</View>
											<View
												pointerEvents="box-none"
												style={{
													position: "absolute",
													left: 26,
													right: 24,
													top: 93,
													height: 19,
													flexDirection: "row",
													alignItems: "flex-start",
												}}>
												<Text
													style={styles.inputDrinkNameTwentySixText}>Runners:</Text>
												<View
													style={{
														flex: 1,
													}}/>
												<View
													style={styles.numberBoxView}>
													<View
														pointerEvents="box-none"
														style={{
															position: "absolute",
															left: 0,
															right: 0,
															top: 0,
															bottom: 0,
															justifyContent: "center",
														}}>
														<Image
															source={require("./../../assets/images/rectangle.png")}
															style={styles.rectangleImage}/>
													</View>
													<View
														pointerEvents="box-none"
														style={{
															position: "absolute",
															left: 0,
															right: 0,
															top: 0,
															bottom: 0,
															justifyContent: "center",
														}}>
														<TextInput 
															value={this.state.Temp[index].runners.toString()}
															keyboardType="number-pad"
															maxLength={3}
															onChangeText={(text) => {this.updateRunner(index, text)}}
															style={styles.textTenText}/>
													</View>
												</View>
											</View>
										</View>
									))
									}
								</View>
								<View
									style={{
										height: 300,
									}}/>
							</ScrollView>
						</View>
					</View>
				</View>
				<View
					style={{
						flex: 1,
					}}/>
				<Image
					source={require("./../../assets/images/plus-circle-3.png")}
					style={styles.plusCircleImage}/>
				<View
					style={styles.savePreorderMenuBView}>
					<Text
						style={styles.savePreorderMenuText}>Finish Stations and Input of Inventory</Text>
				</View>
			</View>
	}
}

const styles = StyleSheet.create({
	scrollView: {
		height: 600,
	},
	viewView: {
		backgroundColor: "rgb(247, 247, 247)",
		flex: 1,
	},
	topImageImage: {
		backgroundColor: "transparent",
		resizeMode: "cover",
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 153,
	},
	backButtonImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 8,
		height: 14,
		marginTop: 3,
	},
	menuButtonImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 4,
		height: 20,
	},
	preorderQueCardView: {
		backgroundColor: "transparent",
		alignSelf: "center",
		width: 314,
		height: 282,
		marginTop: 10,
	},
	backgroundImage: {
		backgroundColor: "transparent",
		shadowColor: "rgba(107, 127, 153, 00.40)",
		shadowRadius: 20,
		shadowOpacity: 1,
		resizeMode: "cover",
		width: null,
		height: 282,
	},
	drinkCardElementsView: {
		backgroundColor: "transparent",
		alignSelf: "stretch",
	},
	drinkNameText: {
		backgroundColor: "transparent",
		color: "rgb(5, 5, 5)",
		fontFamily: "Arial-BoldMT",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "bold",
		textAlign: "left",
		letterSpacing: 0.2,
		alignSelf: "flex-start",
		width: 191,
	},
	seperatorImage: {
		backgroundColor: "transparent",
		resizeMode: "cover",
		width: null,
		height: 1,
		marginRight: 4,
		marginTop: 1,
	},
	inputDrinkNameTwentyText: {
		color: "rgb(92, 90, 90)",
		fontFamily: "Arial-BoldMT",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "bold",
		textAlign: "right",
		backgroundColor: "transparent",
		alignSelf: "flex-end",
		width: 68,
		marginTop: 10,
	},
	inputDrinkNameNineteenText: {
		backgroundColor: "transparent",
		color: "rgb(92, 90, 90)",
		fontFamily: "ArialMT",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		alignSelf: "flex-start",
		width: 62,
		marginLeft: 6,
		marginTop: 1,
	},
	inputDrinkNameEighteenText: {
		color: "rgb(92, 90, 90)",
		fontFamily: "Arial-BoldMT",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "bold",
		textAlign: "center",
		backgroundColor: "transparent",
		width: 68,
	},
	inputDrinkNameTwentyThreeText: {
		color: "rgb(92, 90, 90)",
		fontFamily: "Arial-BoldMT",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "bold",
		textAlign: "center",
		backgroundColor: "transparent",
		width: 68,
	},
	inputDrinkNameText: {
		backgroundColor: "transparent",
		color: "rgb(92, 90, 90)",
		fontFamily: "ArialMT",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 62,
	},
	inputDrinkNameFourText: {
		backgroundColor: "transparent",
		color: "rgb(92, 90, 90)",
		fontFamily: "Arial-BoldMT",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "bold",
		textAlign: "right",
		width: 60,
	},
	unitPerPackView: {
		backgroundColor: "transparent",
		width: 61,
		height: 16,
		marginLeft: 2,
		marginTop: 1,
		flexDirection: "row",
		alignItems: "center",
	},
	inputDrinkNameElevenText: {
		backgroundColor: "transparent",
		color: "rgb(92, 90, 90)",
		fontFamily: "ArialMT",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		width: 28,
	},
	inputDrinkNameTwelveText: {
		backgroundColor: "transparent",
		color: "rgb(92, 90, 90)",
		fontFamily: "ArialMT",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		width: 29,
	},
	inputDrinkNameTwentyOneText: {
		backgroundColor: "transparent",
		color: "rgb(92, 90, 90)",
		fontFamily: "Arial-BoldMT",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "bold",
		textAlign: "left",
		width: 68,
		marginBottom: 1,
	},
	inputDrinkNameTwentyTwoText: {
		backgroundColor: "transparent",
		color: "rgb(92, 90, 90)",
		fontFamily: "Arial-BoldMT",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "bold",
		textAlign: "right",
		width: 60,
	},
	inputDrinkNameThreeText: {
		color: "rgb(92, 90, 90)",
		fontFamily: "Arial-BoldMT",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "bold",
		textAlign: "center",
		backgroundColor: "transparent",
		width: 56,
	},
	editTwoView: {
		backgroundColor: "rgb(0, 112, 247)",
		borderRadius: 7,
		width: 69,
		height: 18,
		marginLeft: 225,
		marginTop: 24,
		justifyContent: "center",
	},
	editTwoText: {
		backgroundColor: "transparent",
		color: "white",
		fontFamily: "ArialMT",
		fontSize: 11,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 13,
		marginRight: 14,
	},
	inputDrinkNameTwentySixText: {
		backgroundColor: "transparent",
		color: "rgb(92, 90, 90)",
		fontFamily: "ArialMT",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 62,
		marginTop: 3,
	},
	textTenText: {
		backgroundColor: "transparent",
		color: "rgb(92, 90, 90)",
		fontFamily: "ArialMT",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		letterSpacing: 0.15,
	},
	plusCircleImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		alignSelf: "flex-end",
		width: 38,
		height: 38,
		marginRight: 30,
		marginBottom: 43,
	},
	savePreorderMenuBView: {
		backgroundColor: "rgb(0, 112, 247)",
		borderRadius: 20,
		shadowColor: "rgba(0, 0, 0, 00.40)",
		shadowRadius: 6,
		shadowOpacity: 1,
		height: 50,
		marginLeft: 20,
		marginRight: 20,
		marginBottom: 15,
		justifyContent: "center",
		alignItems: "center",
	},
	savePreorderMenuText: {
		color: "white",
		fontFamily: "Arial-BoldMT",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "bold",
		textAlign: "center",
		backgroundColor: "transparent",
	},
	numberBoxView: {
		backgroundColor: "transparent",
		width: 23,
		height: 17,
		marginBottom: 5,
		marginLeft: 5,
	},
	rectangleImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 17,
	},
	textText: {
		color: "rgb(92, 90, 90)",
		fontFamily: "ArialMT",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		letterSpacing: 0.15,
		backgroundColor: "transparent",
		marginRight: 1,
	},
})
